routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// MAIN SITE
Route::get('/', function () {
    return view('welcome');
});
Route::get('/aviso-de-privacidad', function () {
    return view('avisoPrivacidad');
});
// SEND EMAIL
Route::post('/sendResume', 'SiteController@sendResume' );
Route::post('/sendContact', 'SiteController@sendContact' );

Auth::routes();
//AJAX ROUTES
Route::get('/ajax/csrf/', 'CsrfController@csrf_');
Route::get('/ajax/sepomex/{cp}', 'AjaxController@sepomex');
Route::get('/ajax/empresasData/{id}', 'AjaxController@empresasData');
Route::get('/ajax/candidatosList/{_userId}/{_roleId}/{_ownerId}/{_vacanteId}', 'AjaxController@candidatosList');
Route::get('/ajax/reclutadorRelations/{id}', 'AjaxController@reclutadorRelations');
Route::get('/ajax/empresasRelations/{id}', 'AjaxController@empresasRelations');

// ADMINS
Route::post('/dashboard/user/delete', 'AdminController@userDelete');
Route::post('/dashboard/users/edit', 'AdminController@update');
Route::post('/dashboard/users/compensaciones/update', 'AdminController@updateCompensaciones');

Route::get('/dashboard/users/profile/{id}', 'AdminController@userProfile');
Route::get('/dashboard/users/edit/{id}', 'AdminController@showEditForm');
Route::get('/dashboard/users/compensaciones/{id}', 'AdminController@showCompensaciones');
Route::get('/dashboard/users/compensaciones/edit/{id}', 'AdminController@editCompensaciones');
Route::get('/dashboard/users/{role_type}', 'AdminController@userList');

Route::get('/dashboard/users/referencias/new/{uid}', 'AdminController@newReferencias');
Route::get('/dashboard/users/referencias/{uid}', 'AdminController@showReferencias');
Route::post('/dashboard/users/referencias/create', 'AdminController@createReferencias');

Route::get('/dashboard/users/referencias/view/{rid}/{uid}', 'AdminController@viewReferencias');
Route::get('/dashboard/users/referencias/edit/{rid}/{uid}', 'AdminController@editReferencias');
Route::post('/dashboard/users/referencias/update', 'AdminController@updateReferencias');
Route::post('/dashboard/users/referencias/delete', 'AdminController@deleteReferencias');

// Registration Routes...
Route::get('/dashboard/users/registration/{role_type}', 'AdminController@showRegistrationForm');
Route::post('/dashboard/users/registration', 'AdminController@create');
// Vacantes
Route::get('/dashboard/vacantes/', 'VacantesController@index');
Route::get('/dashboard/vacantes/export', 'VacantesController@indexExport');

Route::get('/dashboard/vacantes/view/{id}', 'VacantesController@view');
Route::get('/dashboard/vacantes/print/{id}', 'VacantesController@imprimir');
Route::get('/dashboard/vacantes/create/', 'VacantesController@showCreationForm');
Route::post('/dashboard/vacantes/create/', 'VacantesController@create');
Route::get('/dashboard/vacantes/edit/{id}', 'VacantesController@showEditForm');
Route::post('/dashboard/vacantes/edit/', 'VacantesController@update');
Route::post('/dashboard/vacantes/updateComments/', 'VacantesController@updateComments');
Route::post('/dashboard/vacantes/delete/', 'VacantesController@delete');
Route::post('/dashboard/vacantes/addCandidate/', 'VacantesController@addCandidate');
Route::post('/dashboard/vacantes/fileUpload/', 'VacantesController@fileUpload');

Route::get('/dashboard/vacantes/secFits/{uid}/{vid}', 'VacantesController@showSecFits');
Route::get('/dashboard/vacantes/secFits/edit/{uid}/{vid}', 'VacantesController@editSecFits');
Route::get('/dashboard/vacantes/secFits/print/{uid}/{vid}', 'VacantesController@printSecFits');
Route::post('/dashboard/vacantes/secFits/update', 'VacantesController@updateSecFits');

Route::post('/dashboard/vacantes/estatusUser', 'VacantesController@estatusUser');
Route::post('/dashboard/vacantes/blockUser', 'VacantesController@blockUser');
Route::post('/dashboard/vacantes/hireUser', 'VacantesController@hireUser');
Route::post('/dashboard/vacantes/hideCandidate', 'VacantesController@hideCandidate');
Route::post('/dashboard/vacantes/showCandidate', 'VacantesController@showCandidate');

Route::get('/dashboard/sucursalesSectores', 'AdminController@sucursalesSectores');
Route::post('/dashboard/sucursalesSectores/sucursalUpdate', 'AdminController@sucursalesUpdate');
Route::post('/dashboard/sucursalesSectores/sucursalUpload', 'AdminController@sucursalesUpload');
Route::post('/dashboard/sucursalesSectores/sectorUpload', 'AdminController@sectorUpload');
Route::post('/dashboard/sucursalesSectores/sectorUpdate', 'AdminController@sectorUpdate');

// DASHBOARD
Route::get('/dashboard', 'DashboardController@dashboard');
//STORAGE RESTRICTION
Route::get('storage/{folder}/{filename}', 'DashboardController@getFile')->where('filename', '^[^/]+$');

// MI PERFIL
Route::get('/dashboard/my-profile/', 'UserController@myProfile');
// RECLUTADORES

// CANDIDATOS

// EMPRESAS

//Analytics

Route::group(['prefix' => 'dashboard/admin/', 'middleware'=>['auth', 'role:SuperAdmin,Vendedor']], function () {
    
    Route::get('charts', 'AnalyticsController@index');
    Route::get('getOpenVacants', 'AnalyticsController@getOpenVacants');
    Route::get('getClosedVacants', 'AnalyticsController@getClosedVacants');
    Route::get('getVacantsClosedWithHiring', 'AnalyticsController@getVacantsClosedWithHiring');
    Route::get('getVacantsClosedWithOutHiring', 'AnalyticsController@getVacantsClosedWithOutHiring');
    Route::get('getSellers', 'AnalyticsController@getSaleAmount');
    Route::get('opportunities', 'AnalyticsController@viewChart');
    Route::get('getVacantsByEnterprise', 'AnalyticsController@getVacantsByEnterprise');
    Route::get('getVacantsWithAssurance', 'AnalyticsController@getVacantsWithAssurance');

});

// FREELANCE

Route::group(['prefix' => '/dashboard/users', 'middleware' => ['auth','role:SuperAdmin']], function () {
    
    Route::get('/freelances/index', 'FreelanceController@index')->name('freelance.index');
    Route::resource('freelances', 'FreelanceController');

});

Route::get('/dashboard/admin/getTotalSecfits', 'AnalyticsController@getTotalSecfits');
//EMPRESAS-CLIENTES
Route::get('/dashboard/users/profile/{id}/vacantes', 'EnterpriseController@show')->middleware(['auth','role:Empresa'])->name('enterprise.all.vacant');

resources/views/partials/menus/admin.blade.php
    <ul class="navbar-nav">
        <li class="p-2"><strong><a href="{{ url('/dashboard/') }}"><i class="fas fa-home mr-3 font-20"></i> Home</a></strong></li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#reclutadoresMenu').slideToggle();"><i class="fas fa-user-tie mr-3 font-20"></i> HeadHunters <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="reclutadoresMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Reclutador') }}">Ver todos</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Reclutador') }}">Nuevo HeadHunter</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#candidatosMenu').slideToggle();"><i class="fas fa-user mr-3 font-20"></i> Candidatos <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="candidatosMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Candidato') }}">Ver todos</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Candidato') }}">Nuevo candidato</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#empresasMenu').slideToggle();"><i class="far fa-building mr-3 font-20"></i> Empresas <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="empresasMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Empresa') }}">Ver todas</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Empresa') }}">Nueva empresa</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#vacantesMenu').slideToggle();"><i class="fas fa-clipboard-list mr-3 font-20"></i> Vacantes <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="vacantesMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/vacantes') }}">Ver todas</a></li>
                <li><a href="{{ url('/dashboard/vacantes/create') }}">Nueva vacante</a></li>
            </ul>
        </li>
        @if(Auth::user()->hasRole('Vendedor'))
                <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#analyticsMenu').slideToggle();"><i class="fas fa-clipboard-list mr-3 font-20"></i> Analytics <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="analyticsMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/admin/opportunities') }}">Opportunities</a></li>
            </ul>
        </li>
        @endif
    </ul>

resources/views/partials/menus/candidato.blade.php
    <ul class="navbar-nav">
        <li class="p-2"><strong><a href="{{ url('/dashboard/') }}"><i class="fas fa-user mr-3 font-20"></i><span class="mobileHide"> Mi perfil</span></a></strong></li>
        <li class="p-2"><strong><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fas fa-power-off mr-3 font-20"></i><span class="mobileHide"> Cerrar sesión</span></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/') }}"><i class="fas fa-question-circle mr-3 font-20"></i><span class="mobileHide">¿Quién es LEVU?</span></a></strong></li>
        <li class="p-2"><strong><h6><a href="{{ url('/aviso-de-privacidad')}}" target="_blank"><i class="fas fa-user-shield mr-3 font-20"></i><span class="mobileHide">Política de privacidad</span></a></h6></strong></li>
    </ul>

resources/views/partials/menus/empresa.blade.php
    <ul class="navbar-nav">
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/profile/' . Auth::user()->id) }}"><i class="far fa-building mr-3 font-20"></i><span class="mobileHide"> Mi perfil</span></a></strong></li>
        <li class="p-2"><strong><a href="{{ route('enterprise.all.vacant', Auth::user()->id) }}"><i class="fas fa-clipboard-list mr-3 font-20"></i><span class="mobileHide">  Mis vacantes</span></a></strong></li>
    </ul>

resources/views/partials/menus/reclutador.blade.php
    <ul class="navbar-nav mobileHide">
        <li class="p-2"><strong><a href="{{ url('/dashboard/') }}"><i class="fas fa-home mr-3 font-20"></i> Home</a></strong></li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#candidatosMenu').slideToggle();"><i class="fas fa-user mr-3 font-20"></i> Candidatos <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="candidatosMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Candidato') }}">Candidatos</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Candidato') }}">Nuevo candidato</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/Empresa') }}" class="pointer"><i class="far fa-building mr-3"></i> Clientes</strong></li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#vacantesMenu').slideToggle();"><i class="fas fa-clipboard-list mr-3 font-20"></i> Vacantes <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="vacantesMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/vacantes') }}">Mis vacantes</a></li>
                <li><a href="{{ url('/dashboard/vacantes/create') }}">Nueva vacante</a></li>
            </ul>
        </li>
    </ul>
    <ul class="navbar-nav mobileShow">
        <li class="p-2"><strong><a href="{{ url('/dashboard/') }}"><i class="fas fa-home mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/Candidato') }}" class="pointer" onclick="$('#candidatosMenu').slideToggle();"><i class="fas fa-user mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/Empresa') }}" class="pointer"><i class="far fa-building font-20 mr-3"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/vacantes') }}" class="pointer" onclick="$('#vacantesMenu').slideToggle();"><i class="fas fa-clipboard-list mr-3 font-20"></i></a></strong></li>
    </ul>
    

resources/views/partials/menus/superAdmin.blade.php
    <ul class="navbar-nav mobileHide">
        <li class="p-2"><strong><a href="{{ url('/dashboard/') }}"><i class="fas fa-home mr-3 font-20"></i> Home</a></strong></li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#adminMenu').slideToggle();"><i class="fas fa-user-secret mr-3 font-20"></i> Admins <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="adminMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/registration/Admin') }}">Nuevo admin</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#reclutadoresMenu').slideToggle();"><i class="fas fa-user-tie mr-3 font-20"></i> HeadHunters <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="reclutadoresMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Reclutador') }}">Ver todos</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Reclutador') }}">Nuevo HeadHunter</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#freelanceMenu').slideToggle();"><i class="fas fa-user-friends mr-3 font-20"></i> Freelance <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="freelanceMenu" style="display:none;">
                <li><a href="{{ route('freelance.index') }}">Ver todos</a></li>
                <li><a href="{{ route('freelances.create') }}">Nuevo freelance</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#candidatosMenu').slideToggle();"><i class="fas fa-user mr-3 font-20"></i> Candidatos <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="candidatosMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Candidato') }}">Ver todos</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Candidato') }}">Nuevo candidato</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#empresasMenu').slideToggle();"><i class="far fa-building mr-3 font-20"></i> Empresas <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="empresasMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/users/Empresa') }}">Ver todas</a></li>
                <li><a href="{{ url('/dashboard/users/registration/Empresa') }}">Nueva empresa</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#vacantesMenu').slideToggle();"><i class="fas fa-clipboard-list mr-3 font-20"></i> Vacantes <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="vacantesMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/vacantes') }}">Ver todas</a></li>
                <li><a href="{{ url('/dashboard/vacantes/create') }}">Nueva vacante</a></li>
            </ul>
        </li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/sucursalesSectores') }}"><i class="fas fa-industry mr-3 font-20"></i> Sucursales y sectores</a></strong></li>
        <li class="p-2"><strong><a href="#" class="pointer" onclick="$('#analiticosMenu').slideToggle();"><i class="fas fa-chart-bar mr-3 font-20"></i> Analíticos <i class="fas fa-chevron-down font-9"></i></a></strong>
            <ul class="nav-link pl-5 mb-3" id="analiticosMenu" style="display:none;">
                <li><a href="{{ url('/dashboard/admin/charts') }}">Consulta gráficas</a></li>
            </ul>
        </li>
    </ul>
    <ul class="navbar-nav mobileShow">
        <li class="p-2"><strong><a href="{{ url('/dashboard/') }}"><i class="fas fa-home mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/registration/Admin') }}"><i class="fas fa-user-secret mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/Reclutador') }}"><i class="fas fa-user-tie mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/Candidato') }}"><i class="fas fa-user mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/users/Empresa') }}"><i class="far fa-building mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/vacantes') }}"><i class="fas fa-clipboard-list mr-3 font-20"></i></a></strong></li>
        <li class="p-2"><strong><a href="{{ url('/dashboard/admin/charts') }}"><i class="fas fa-chart-bar mr-3 font-20"></i></a></strong></li>
    </ul>